### ISSUE TITLE
Multiple scopes validation

### ISSUE THREAD

**Issue by filipwiniarski** [amannn/action-semantic-pull-request#140]
Hi, is there any way to handle multiple scopes, comma seperated?

My desired goal is to either have the validation by default, or to configure regex to pass such title:
`feat(core, ui, cdk, ...): do this`

Maybe it would be nice to add a `multipleScopes` flag to the configuration:
```yml
with:
  ...
  multipleScopes: true
  ...
```
