### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by akornatskyy** [amannn/action-semantic-pull-request#173]
When I use this action in a private repository I receive the following error: "Resource not accessible by integration"... I tried to add permissions (but that doesn't help much):

```yaml
jobs:
  main:
    permissions:
      statuses: write
```

it is also impossible from error to say which operation particularly fails. Thoughts?
