### ISSUE TITLE
Classify type of PR based on Diff file path rules

### ISSUE THREAD

**Issue by jthegedus** [amannn/action-semantic-pull-request#186]
## What

I would like to configure and assert errors of specific types/scopes to code changes in the PR diff.

For instance, if I have a PR with `docs:` as the type/scope I want to ensure this is only applied when the PR contains changes **only** to the documentation, that is, a list of files or dirs.

## Why

Users will create PRs with `fix:` type, but really they're updating some CI, Tests or Docs which should be captured under `ci:`, `tests:` or `docs:` types. This is important with Changelogs generated from semantic commits. It would be useful to assert these types of requirements so that I do not have to remember to check the actual code change aligns with the semantic type myself, because I make mistakes a lot 😅 

## Example

An example of what this would look like in configuration:

```yaml
name: Lint PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  semantic-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          typeWhenOnlyPaths:
             - docs:
               - docs/*
               - README.md
             - ci:
               - .github/*
             - tests:
               - tests/*
```

So from this config, PRs with changes only in `docs/*` or `README.md` can then only have the `docs:` type applied. If it has a different type it errors.

#### Success PR:

```
Title/commit: "docs: changing just docs"
Files changed:
- README.md
- docs/index.md
```

#### Failure PR:

```
Title/commit: "fix: typo in docs"
Files changed:
- docs/index.md
```

Wrong `type` for changes in Paths. Should have `type` of `docs:`, found `fix:`

#### Failure PR:

```
Title/commit: "fix: typo in ci pipeline"
Files changed:
- .github/workflows/test.yml
```

Wrong `type` for changes in Paths. Should have Type of `ci:`, found `fix:`

### More changes detected

If changes occur in more than one of the  `typeWhenOnlyPaths` then the rules are ignored, they only apply when ONLY those paths are present.

Success PR:

```
Title/commit: "fix: typo in ci pipeline"
Files changed:
- .github/workflows/test.yml
- docs/index.md
```

No rules under `typeWhenOnlyPaths` match, so the `fix:` type cannot be asserted by this configuration.

## Caveats

This is useful for avoiding simple issues, but doesn't help classify changes to multiple areas of the code at once. Though, due to the more complex review requirements when multiple areas are updated, complex changes aren't subject to the same simple errors I would like to capture with this type of feature.

---

Thanks for the great GitHub Action 👏
