### ISSUE TITLE
Make scopes and types YAML lists

### ISSUE THREAD

**Issue by jszwedko** [amannn/action-semantic-pull-request#203]
Hey all,

We'd like to have comments around our lists of types and scopes but because they are YAML scalars, this isn't possible. For example, we'd like to write:

```yaml
        with:
          types: |
            chore               # An internal change this is not observable by users.
            enhancement         # Any user observable enhancement to an existing feature.
```

But the comments are included in the scalar.

Ideally we could provide the types and scopes as actual lists like:

```
        with:
          types: |
          - chore               # An internal change this is not observable by users.
          - enhancement         # Any user observable enhancement to an existing feature.
```

Is there a reason the types and scopes are newline delimited strings rather than being YAML lists? Would you be open to a (breaking) PR changing that?
