### ISSUE TITLE
Use regex when comparing header types

### ISSUE THREAD

**Issue by sidlatau** [amannn/action-semantic-pull-request#220]
**Is your feature request related to a problem? Please describe.**

I am using custom regex for allowed types:
```yml
headerPattern: '^(feat:|fix:|chore:|refact:|ci:|docs:|\[axof: \d+\]|\[axod: \d+\]) (.*)$'
```
As I understand I need to list all available types. But some of the types are regexes. The list looks like this:
```yml
          types: |
            feat:
            fix:
            chore:
            refact:
            ci:
            docs:
            [axof: \d+]
            [axod: \d+]
```

The problem is that regexes does not work for types, because `types.includes(result.type)` is used for the check.

**Describe the solution you'd like**

I would want to treat types as regexes:
```js
function isUnknownType(type) {
    for (type of types) {
      const regex = new RegExp(type);
      if (regex.test(result.type)) {
        return false;
      }
    }
    return true;
  }
 ...
   if (isUnknownType(result.type)) {
    raiseError(
      `Unknown release type "${
      result.type
      }" found in pull request title "${prTitle}". \n\n${printAvailableTypes()}`
    );
  }
```
I have a working code in forked repository: 
https://github.com/amannn/action-semantic-pull-request/compare/main...sidlatau:regex-title?expand=1
 
Would it be possible/useful for others to add such functionality in this action? Or maybe there is an other way how to do it without code changes?
