### ISSUE TITLE
docs: miss permission for statuses: write

### ISSUE THREAD

**Issue by cebidhem** [amannn/action-semantic-pull-request#233]
**Is your feature request related to a problem? Please describe.**

It's not really a feature, but I was unable to make the action work with only `permissions.pull-requests: read`. 

I had to add `permissions.statuses: write`. Indeed, after trying a lot of combinations, I tried `permissions: write-all` and noticed a new status check added.
I don't know why I seem to be the only one though 🤔 The action runs in a public repo with the Action `GITHUB_TOKEN`.

**Describe the solution you'd like**

Add the mention in the docs. I'm willing to open a doc PR if you agree!

**Describe alternatives you've considered**

None.

**Comment by amannn** [comment]
Thanks for the report! In this repository [the action works with the documented settings](https://github.com/amannn/action-semantic-pull-request/blob/3bb5af3c0c8f5e85d328728c1ab68dd6cefd03af/.github/workflows/lint-pr-title.yml#L9-L10) so I guess there's some difference in your environment?

Are you using [the `wip` feature](https://github.com/amannn/action-semantic-pull-request/tree/main#work-in-progress-pull-requests), where `write` access is necessary?

In any case, a reproduction would be necessary to discuss this further.

**Comment by xdyfekete** [comment]
joining this :)
Only when I added the statuses: write, it started working.
It also doesn't throw any error if it misses permissions.

**Comment by paduszyk** [comment]
I'm into this discussion. My setup (it works!):

```yaml
name: Semantic Pull Request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read
  statuses: write
  
jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request title
        uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
```

@cebidhem - indeed, `statuses: write` solves the problem: `Resource not accessible by integration` error in my case. It seems to be legit, as the `statuses` scope is somewhat related to the `wip` input.
