### ISSUE TITLE
I am getting This action can only be invoked in `pull_request_target` or `pull_request` events. Otherwise the pull request can't be inferred.

### ISSUE THREAD

**Issue by soseki-angfa** [amannn/action-semantic-pull-request#237]
**Describe the bug**

I am getting "This action can only be invoked in `pull_request_target` or `pull_request` events. Otherwise the pull request can't be inferred." after pull request merged and action is kicked.

I have following action.

```
name: ci
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  title-lint:
    name: Validate PR commit title meets commit convention
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        scopes: |
          dbt
          pipeline
          jupyternotebook
          analysis
        requireScope: true
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - uses: pre-commit/action@v3.0.0
      env:
        SKIP: sqlfluff-lint,sqlfluff-fix
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: PyTest
      run: |
        python -m pytest tests/unittest --junit-xml results/pytest.xml
      continue-on-error: true
    - name: Upload Unit Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: results/*.xml
    - name: Download Artifacts
      if: success() || failure()
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: artifacts/**/*.xml
```

I have following result.

![image](https://github.com/amannn/action-semantic-pull-request/assets/106799197/adbd2767-f56d-4719-9f08-86b571732dd1)

Even I re-run only failed job, I got this error.
Do you have any idea for this idea?
