### ISSUE TITLE
Can't add a custom prefix that has space in it e.g `BREAKING CHANGE`

### ISSUE THREAD

**Issue by pof-jhansilva** [amannn/action-semantic-pull-request#257]
**Is your feature request related to a problem? Please describe.**

Hey, so we are using semantic-release to create our Github Releases using the following prefix table

![image](https://github.com/amannn/action-semantic-pull-request/assets/146135120/2d4f0a0f-323a-41f2-a308-32217c5e3f58)

I wanted to add BREAKING CHANGE: as a valid prefix because `semantic-release` uses it to create major/breaking releases but when I try it it just errors out.

Example of configuration:

````YAML
- name: Validate semantic title 🔡
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            perf
            BREAKING CHANGE
````

But even after adding that it still errors out with:

````
Error: No release type found in pull request title "BREAKING CHANGE". Add a prefix to indicate what kind of release this pull request corresponds to. For reference, see https://www.conventionalcommits.org/

Available types:
 - fix
 - feat
 - perf
 - BREAKING CHANGE
 
````

**Describe the solution you'd like**

Be able to add BREAKING CHANGE as an acceptable prefix so we can use it together with this [action](https://github.com/cycjimmy/semantic-release-action/blob/main/src/windUpJob.task.js)
  
**Describe alternatives you've considered**

Using `perf` prefix that is accepted by the conventionalcommits but sometimes this doesn't reflect the type of change that we are introducing.
