### ISSUE TITLE
Error: Unknown scope while using valid scope

### ISSUE THREAD

**Issue by damnitrahul** [amannn/action-semantic-pull-request#267]
**Describe the bug**

I've setup the action to lint PR titles along with `requireScope: true` and provided the scope. But the lint results in an error. 

```bash
Error: Unknown scope "SKIP" found in pull request title "feat(SKIP): add pr title lint". Scope must match one of: - WEB-\d+, - SKIP.
```

**To reproduce**

lint-title.yml

```yml
name: 'Lint PR Title'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          scopes: |
            - WEB-\d+
            - SKIP

```

PR title
```
feat(SKIP): add pr title lint
chore:(WEB-124): add pr title lint
```

**Expected behavior**

the checks should pass based when correct scopes are provided
