### ISSUE TITLE
Reduce reporting to a singe check or add option to disable WIP

### ISSUE THREAD

**Issue by jsumners** [amannn/action-semantic-pull-request#27]
I have a simple test repo where I am exploring usage of this action. I created a branch on this repo, added some text to a markdown file, and pushed up a commit with an invalid message. The resulting PR reports a status like:

![image](https://user-images.githubusercontent.com/321201/93352293-adf28380-f808-11ea-9e3c-36f909dbe60b.png)

I have a `.github/workflows/pr-commit-lint.yml` file that looks like:

```yaml
name: 'Lint Commit Messages'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Is this expected behavior?
