### ISSUE TITLE
Auto close pull request for exception with conventional commits specification

### ISSUE THREAD

**Issue by AXIM0S** [amannn/action-semantic-pull-request#82]
Hi.
It would be really nice if this action could deal with non-conventional commits in PRs.
Thank you.

**Comment by amannn** [comment]
Hello @AXIM0S,

this action is currently only concerned with the pull request title and not with commits. At the moment I don't want to extend the scope, so possibly this action works better for your use case: https://github.com/wagoid/commitlint-github-action.

If you want to close PRs based on failed PR title linting from this action, maybe this works for you (not tested):

```yml
name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: superbrothers/close-pull-request@v3
        if: failure()
```
