### ISSUE TITLE
README.md example references old version

### ISSUE THREAD

**Issue by bhayes-zd** [amannn/action-semantic-pull-request#92]
## Description

Hey there!

Looks like the README for this project is referencing an older release of the action. The version 3.1.0 appears to not support the `subjectPatternError:` field and logs a warning. So it's possible users might be copy and pasting your example and then getting confused when the `subjectPatternError:` doesn't work.

## Problem Section 🐞 

```yaml
   steps:
      - uses: amannn/action-semantic-pull-request@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## Recommended Change 💡 

> Could either update it to the latest version `@v3.4.0` or put `@master` to automatically
> stay valid for folks as you push new releases.

```yaml
   steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
